import React from 'react';
import './App.css';
import Banner from './components/Banner';
import Categories from './components/Categories';
import { Metadata } from 'next'



export const metadata: Metadata = {
  title: 'Biblioteca | Luis Miguel Urbez',
  description: 'Generated by Luis Miguel Urbez',
}

function App() {

  return (
    <div className="bg-robin-egg-blue min-h-screen">
      <Banner />
      <Categories />
      <hr/>

    </div>
  );
}

export default App;