import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Nunito} from "next/font/google";
import React from "react";
import ClientOnly from './components/ClientOnly'
import Banner from './components/banner/Banner'
import LoginModal from './components/modals/LoginModal'
import LibroModal from './components/modals/LibroModal'
import RegisterModal from './components/modals/RegisterModal'
import SearchModal from './components/modals/SearchModal'
import ToasterProvider from './providers/ToastProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Biblioteca | Luis Miguel Urbez',
  description: 'Generated by Luis Miguel Urbez',
}

const font = Nunito({
  subsets: ['latin']
});

export default async function RootLayout({
                                           children,
                                         }: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
    <body className={font.className}>
    <ClientOnly>
      <ToasterProvider/>
      <SearchModal/>
      <LibroModal/>
      <LoginModal/>
      <RegisterModal/>
      <Banner />
    </ClientOnly>
    <div className="pb-20 pt-28">

      {children}
    </div>
    </body>
    </html>
  )
}

